spring:
  application:
    name: gestion_utilisateur
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    driver-class-name: org.postgresql.Driver
    username: hels
    password: hels
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.filter.OncePerRequestFilter: DEBUG
    org.springdoc: DEBUG

jwt:
  secret: Y7zQ5V0gP2wX4cH8aF1jB9kL7nM6oR3sT2uV1eZ0yW9xC8cD7fE6gH5iJ4kL3mN2oP1qR0sT9uV8wX7yZ6aB5cD4eF3gH2iJ1kL0mN9oP8qR7sT6uV5wX4yZ3aB2cD1eF0gH
  expiration: 86400000